### ISSUE TITLE
Remove distasteful quit messages

### ISSUE THREAD

**Issue by pbates5** [EmeraldCoasttt/BrutalDoomPlatinum#48]
So I play games to take my mind off the troubles of the world, especially classic games like this where you can spend hours mindlessly dispatching demons. I have to say I really don't appreciate whoever shoehorned these overtly political, self absorbed quit messages in this version of Brutal Doom Platinum. I find passive aggressive platitudes like "Black Lives Matter" and "Trans Rights" being thrown at the player every time they quit the application to be a very shortsighted and narcissistic decision by whichever dev chose to include them. I was able to edit the .pk3 and remove these messages after downloading the file, but I think most people would appreciate not having this communist garbage shoved in their face in a completely irrelevant game.

It's a shame because I do enjoy the gameplay changes from v3.1.1 so far.

**Comment by EmeraldCoasttt** [comment]
Never. Trans rights.

**Comment by FelesNoctis** [comment]
> communist garbage

![lul, get a load of this guy](https://github.com/EmeraldCoasttt/BrutalDoomPlatinum/assets/16215725/9e6925e9-34d6-45fc-82c6-a2bb7bd29bdc)

**Comment by pbates5** [comment]
Do you remember this post you made on zdoom forums a year ago?

"Thank you for all of your support, it's an honour to continue Dox's Personalized Brutal Doom as he moves on to bigger and better things, and I believe I can live up to your expectations! ~EmeraldCoasttt"

What happened to this display of humility? Or was it all a show? You seem to have a genuinely pathetic attitude, so needlessly spiteful to players and people you don't know. Is this a response to Sergeant Mark's past behavior? I'm a rather liberal minded person but this is objectively unprofessional.

But it doesn't matter anyway, this version is greatly inferior to previous versions. I have no idea why you decided to strip away the signature execution animations and replace it with an utterly broken melee combat system with ridiculous knockback. You can do whatever you want though, you and this version of BDP are clearly a lost cause. I'll stick with v3.1, made by much more competent and professional people then yourself. What a mistake to leave a cretin like you in charge.

**Comment by FelesNoctis** [comment]
> I'll stick with v3.1, made by much more competent and professional people then yourself. What a mistake to leave a cretin like you in charge. 

You're hilarious. Emerald was also the lead dev and project manager for 3.1. And 3.0. And has been in that position since mid-late 2021. Dox's is still available if you want it, though don't count on him caring you exist either. 

To have seen those messages already, you either got pretty 'lucky' to pull them out of the five dozen exit messages currently in the mod, or you deliberately went looking for them. If these *random messages you only see on record* are what you have problems with in a game and mod dedicated to blood, gore, and extremely graphic violence, and you're a liberal-minded person like you claim, then you're being the definition of "snowflake" the conservative right claims us to be. If you're just claiming that in some bid to reinforce whatever point you think you're making, well, the the "snowflake" title still applies.

Either way, the BDP community is very inclusive and supportive of *Human Rights* as a generality, and people with opinions like what you're expressing can take a hike. It takes a special kind of self-righteous bigotry to try and make the argument you are.

![jog on](https://github.com/EmeraldCoasttt/BrutalDoomPlatinum/assets/16215725/187a8687-8abb-485c-9bec-aa8f78d5877e)

**Comment by pbates5** [comment]
Buddy, I'm well versed and aware of this little shtick you obnoxious dirtbag leftists play, please don't try to pull this "we care about human rights" crap, this has nothing to do with empathy and everything to do with attention. I have never once seen the phrase "Black Lives Matter" or "Trans Rights" used in any context other than to explicitly annoy and spite others, they're literally meaningless picket sign slogans. I say "meaningless" because not a single person I've ever asked can tell me what a "trans right" is, and spouting "black lives matter" to everyone you meet only seems to imply, by default, they don't matter. Inserting them in unwarranted social situations, or say an irrelevant video game, only ever comes across as patronizing and passive aggressive. You're actively pushing people away by acting like this, I refuse to believe you're so delusional you think anyone would be convinced of your beliefs of equality because you spouted slogans at them, I know that you know you're doing it specifically to spite and aggravate other people. Take for example how emerald simply dismissed by concern, closed the ticket, and said "Trans Rights" as if I don't already hold such views. It's childish, it's narcissistic, and it's just pathetic.

By the way I didn't go "looking for these messages", when I was editing the .enu file to remove them there were only about 50 total. It only took me about 3 play sessions before seeing them, they're clearly not the hidden easter eggs you think they are.

And judging from the state of this current version I think it's safe to assume emeraldcoasttt's contributions to this project are vastly exaggerated. Most modders know Dox and Sgt Mark IV are the real heroes of this mod. I've been a loyal fan of this Brutal Doom fork for years but it seems like you and everyone else currently involved are actively trying to tear down everything they've built. I'll just wait for the upcoming BDv22, that looks promising, and Sgt Mark still seems like an upstanding guy who actually shows gratitude towards people who play his mods.

**Comment by EmeraldCoasttt** [comment]
It looks like these messages are doing exactly what they're intended to do, make the people who otherwise feel unwelcome in the brutal doom space know they're valued, and weeding out the snowflakes like you that think a message of acceptance is antithetical to what doom is about. Do you have anything better to do with your life than have a meltdown over 3 strings of text in a free mod for a 30 year old videogame?

**Comment by EmeraldCoasttt** [comment]
It looks like these quit messages are doing exactly what they're designed to; let people that are otherwise unwelcome in the brutal doom community know that they're appreciated, and weeding out losers like you that think a message of acceptance is antithetical to what doom is about. Do you really not have anything better to do than have a meltdown over three strings of text in a free mod for a 30 year old videogame?
